name: Generate GitHub Trophies

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

  push:
    branches:
      - main

permissions:
  contents: write
  issues: read
  pull-requests: read

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Trophy SVG
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: DragonB0i
          file: trophy.svg
          theme: discord
          no-frame: true
          max-rows: 2
          max-cols: 4
          token: ${{ secrets.GH_PAT }}

      - name: Commit Trophy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add trophy.svg

          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "Update trophy.svg"
            git push
          fi
